
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 13;
  public static final int PAR_A = 3;
  public static final int OP_GE = 10;
  public static final int TRUE = 11;
  public static final int OP_EQ = 6;
  public static final int OP_LE = 9;
  public static final int EOF = 0;
  public static final int OP_GT = 8;
  public static final int IF = 2;
  public static final int FALSE = 12;
  public static final int ID = 14;
  public static final int error = 1;
  public static final int OP_LT = 7;
  public static final int PUNTOYCOMA = 5;
  public static final int PAR_C = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "PAR_A",
  "PAR_C",
  "PUNTOYCOMA",
  "OP_EQ",
  "OP_LT",
  "OP_GT",
  "OP_LE",
  "OP_GE",
  "TRUE",
  "FALSE",
  "NUM",
  "ID"
  };
}

